### ISSUE TITLE
Error format

### ISSUE THREAD

**Issue by Purcs3d** [Purcs3d/phishing-softhouse#134]
Error should be formatted and presented in a more appealing way (other than just being pushed off to the side)

**Comment by Itggot-lukas-einlerlarsson** [comment]
Databasen kan enbart hantera strängar på detta sätt: 'sträng' och inte "sträng" -> om en report ska in i databasen får den alltså inte ha denna symbolen i sig: '

**Comment by Purcs3d** [comment]
Resolved in branch #141
